name       : libxml2
version    : 2.9.7
release    : 18
source     :
    - http://xmlsoft.org/sources/libxml2-2.9.7.tar.gz : f63c5e7d30362ed28b38bfa1ac6313f9a80230720b7fb6c80575eeab3ff5900c
license    :
    - MIT
component  : system.base
summary    : GNOME XML Library
description: |
    The libxml2 package contains libraries and utilities used for parsing XML files.
builddeps  :
    - pkgconfig32(liblzma)
    - pkgconfig32(zlib)
    - glibc-32bit-devel
    - libgcc-32bit
optimize   : speed
devel      : yes
emul32     : yes
patterns   :
    - docs : /usr/share/doc
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        %configure --disable-static --prefix=/usr --without-python
    else
        %configure --disable-static --prefix=/usr
    fi
build      : |
    %make
install    : |
    %make_install
    install -m 00755 $pkgfiles/buildDocBookCatalog $installdir/usr/bin/buildDocBookCatalog
profile    : |
    # Clear Inspiration.
    %make dba100000.xml
    ./xmllint --noout  dba100000.xml
    ./xmllint --stream  dba100000.xml
    ./xmllint --noout --valid test/valid/REC-xml-19980210.xml
    ./xmllint --stream --valid test/valid/REC-xml-19980210.xml
check      : |
    %make check
