name       : libxml2
version    : 2.9.8
release    : 21
source     :
    - https://github.com/GNOME/libxml2/archive/v2.9.8.tar.gz : ff879b0d9142564bfe63df9753df936f05150afdd7bae07261f12d4dad33ba4a
license    :
    - MIT
component  : system.base
summary    : GNOME XML Library
description: |
    The libxml2 package contains libraries and utilities used for parsing XML files.
builddeps  :
    - pkgconfig32(liblzma)
    - pkgconfig32(zlib)
    - pkgconfig(python3)
autodep    : no
optimize   : speed
devel      : yes
emul32     : yes
patterns   :
    - docs : /usr/share/doc
rundeps    :
    - 32bit :
        - glibc-32bit
        - xz-32bit
        - zlib-32bit
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2018-9251.patch
    %patch -p1 < $pkgfiles/security/cve-2018-14404.patch

    if [[ ! -z "${EMUL32BUILD}" ]]; then
        %reconfigure --disable-static --prefix=/usr --without-python
    else
        pushd ..
            cp -a libxml2-$version python3
            mv python3 libxml2-$version/
        popd
        pushd python3
            %reconfigure --disable-static --prefix=/usr --with-python=/usr/bin/python3
        popd
        %reconfigure --disable-static --prefix=/usr --with-python=/usr/bin/python2
    fi
build      : |
    if [[ -z "${EMUL32BUILD}" ]]; then
        %make -C python3
    fi
    %make
install    : |
    if [[ -z "${EMUL32BUILD}" ]]; then
        %make_install -C python3
    fi
    %make_install
    install -m 00755 $pkgfiles/buildDocBookCatalog $installdir/usr/bin/buildDocBookCatalog
profile    : |
    # Clear Inspiration.
    %make dba100000.xml
    ./xmllint --noout  dba100000.xml
    ./xmllint --stream  dba100000.xml
    ./xmllint --noout --valid test/valid/REC-xml-19980210.xml
    ./xmllint --stream --valid test/valid/REC-xml-19980210.xml
check      : |
    %make check
