name       : libxml2
version    : 2.9.8
release    : 20
source     :
    - http://xmlsoft.org/sources/libxml2-2.9.8.tar.gz : 0b74e51595654f958148759cfef0993114ddccccbb6f31aee018f3558e8e2732
license    :
    - MIT
component  : system.base
summary    : GNOME XML Library
description: |
    The libxml2 package contains libraries and utilities used for parsing XML files.
builddeps  :
    - pkgconfig32(liblzma)
    - pkgconfig32(zlib)
    - pkgconfig(python3)
autodep    : no
optimize   : speed
devel      : yes
emul32     : yes
patterns   :
    - docs : /usr/share/doc
rundeps    :
    - 32bit :
        - glibc-32bit
        - xz-32bit
        - zlib-32bit
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2018-9251.patch
    %patch -p1 < $pkgfiles/security/cve-2018-14404.patch

    if [[ ! -z "${EMUL32BUILD}" ]]; then
        %configure --disable-static --prefix=/usr --without-python
    else
        pushd ..
            cp -a libxml2-$version python3
            mv python3 libxml2-$version/
        popd
        pushd python3
            %configure --disable-static --prefix=/usr --with-python=/usr/bin/python3
        popd
        %configure --disable-static --prefix=/usr --with-python=/usr/bin/python2
    fi
build      : |
    if [[ -z "${EMUL32BUILD}" ]]; then
        %make -C python3
    fi
    %make
install    : |
    if [[ -z "${EMUL32BUILD}" ]]; then
        %make_install -C python3
    fi
    %make_install
    install -m 00755 $pkgfiles/buildDocBookCatalog $installdir/usr/bin/buildDocBookCatalog
profile    : |
    # Clear Inspiration.
    %make dba100000.xml
    ./xmllint --noout  dba100000.xml
    ./xmllint --stream  dba100000.xml
    ./xmllint --noout --valid test/valid/REC-xml-19980210.xml
    ./xmllint --stream --valid test/valid/REC-xml-19980210.xml
check      : |
    %make check
