name        : libxml2
version     : 2.9.3
release     : 11
source      :
    - http://xmlsoft.org/sources/libxml2-2.9.2.tar.gz : 5178c30b151d044aefb1b08bf54c3003a0ac55c59c866763997529d60770d5bc
license     :
    - MIT
summary     : GNOME XML Library
description : |
    The libxml2 package contains libraries and utilities used for parsing XML files.
optimize   : speed
devel      : yes
patterns   :
    - docs: /usr/share/doc
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    install -m 00755 $pkgfiles/buildDocBookCatalog $installdir/usr/bin/buildDocBookCatalog
profile    : |
    %make dba100000.xml
    ./xmllint --noout  dba100000.xml
    ./xmllint --stream  dba100000.xml
    ./xmllint --noout --valid test/valid/REC-xml-19980210.xml
    ./xmllint --stream --valid test/valid/REC-xml-19980210.xml
check     : |
    %make check
