name        : libxml2
version     : 2.9.3
release     : 12
source     :
    - http://xmlsoft.org/sources/libxml2-2.9.3.tar.gz : 4de9e31f46b44d34871c22f54bfc54398ef124d6f7cafb1f4a5958fbcd3ba12d
license     :
    - MIT
summary     : GNOME XML Library
description : |
    The libxml2 package contains libraries and utilities used for parsing XML files.
optimize   : speed
devel      : yes
patterns   :
    - docs: /usr/share/doc
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    install -m 00755 $pkgfiles/buildDocBookCatalog $installdir/usr/bin/buildDocBookCatalog
profile    : |
    %make dba100000.xml
    ./xmllint --noout  dba100000.xml
    ./xmllint --stream  dba100000.xml
    ./xmllint --noout --valid test/valid/REC-xml-19980210.xml
    ./xmllint --stream --valid test/valid/REC-xml-19980210.xml
check     : |
    %make check
