name       : libxml2
version    : 2.9.4
release    : 15
source     :
    - http://xmlsoft.org/sources/libxml2-2.9.4.tar.gz : ffb911191e509b966deb55de705387f14156e1a56b21824357cdf0053233633c
license    :
    - MIT
summary    : GNOME XML Library
description: |
    The libxml2 package contains libraries and utilities used for parsing XML files.
builddeps  :
    - pkgconfig32(liblzma)
    - pkgconfig32(zlib)
    - glibc-32bit-devel
    - libgcc-32bit
optimize   : speed
devel      : yes
emul32     : yes
patterns   :
    - docs : /usr/share/doc
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        %configure --disable-static --prefix=/usr --without-python
    else
        %configure --disable-static --prefix=/usr
    fi
build      : |
    %make
install    : |
    %make_install
    install -m 00755 $pkgfiles/buildDocBookCatalog $installdir/usr/bin/buildDocBookCatalog
profile    : |
    # Clear Inspiration.
    %make dba100000.xml
    ./xmllint --noout  dba100000.xml
    ./xmllint --stream  dba100000.xml
    ./xmllint --noout --valid test/valid/REC-xml-19980210.xml
    ./xmllint --stream --valid test/valid/REC-xml-19980210.xml
check      : |
    %make check
