name       : libxml2
version    : 2.9.14
release    : 31
source     :
    - https://github.com/GNOME/libxml2/archive/refs/tags/v2.9.14.tar.gz : 77e7c7240ce447582d2c3471f050423c01ec0e201c3bf2fd6731064d1891f362
license    :
    - MIT
component  : system.base
summary    : GNOME XML Library
description: |
    The libxml2 package contains libraries and utilities used for parsing XML files.
builddeps  :
    - pkgconfig32(liblzma)
    - pkgconfig32(zlib)
    - pkgconfig(python3)
autodep    : no
optimize   : speed
devel      : yes
emul32     : yes
patterns   :
    - docs : /usr/share/doc
rundeps    :
    - 32bit :
        - glibc-32bit
        - xz-32bit
        - zlib-32bit
setup      : |
    %apply_patches
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        %reconfigure --disable-static --without-python
    else
        pushd ..
            cp -a libxml2-$version python3
            mv python3 libxml2-$version/
        popd
        pushd python3
            %reconfigure --disable-static --with-python=/usr/bin/python3
        popd
        %reconfigure --disable-static --with-python=/usr/bin/python2
    fi
build      : |
    if [[ -z "${EMUL32BUILD}" ]]; then
        %make -C python3
    fi
    %make
install    : |
    if [[ -z "${EMUL32BUILD}" ]]; then
        %make_install -C python3
    fi
    %make_install
    install -m 00755 $pkgfiles/buildDocBookCatalog $installdir/usr/bin/buildDocBookCatalog
profile    : |
    # Clear Inspiration.
    %make dba100000.xml
    ./xmllint --noout  dba100000.xml
    ./xmllint --stream  dba100000.xml
    ./xmllint --noout --valid test/valid/REC-xml-19980210.xml
    ./xmllint --stream --valid test/valid/REC-xml-19980210.xml
    %make check
#check      : |
#    %make check
