name       : libxml2
version    : 2.10.3
release    : 35
source     :
    - https://github.com/GNOME/libxml2/archive/refs/tags/v2.10.3.tar.gz : 3f9fb74bb02049f3454892c88d3e57a23e30a88a7d444a80064625af2f543898
license    :
    - MIT
component  : system.base
summary    : GNOME XML Library
description: |
    The libxml2 package contains libraries and utilities used for parsing XML files.
builddeps  :
    - pkgconfig32(liblzma)
    - pkgconfig32(zlib)
    - pkgconfig(python3)
autodep    : no
optimize   : speed
devel      : yes
emul32     : yes
patterns   :
    - docs : /usr/share/doc
rundeps    :
    - 32bit :
        - glibc-32bit
        - xz-32bit
        - zlib-32bit
environment: |
    # set common build options here to avoid copy pasta spam.
    export COMMON_OPTS="--disable-static --with-python --with-legacy --with-ftp --with-xptr-locs"
    export PYTHON=/usr/bin/python3
setup      : |
    %apply_patches
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        %reconfigure $COMMON_OPTS --without-python
    else
        %reconfigure $COMMON_OPTS
    fi
build      : |
    %make
install    : |
    %make_install
    install -m 00755 $pkgfiles/buildDocBookCatalog $installdir/usr/bin/buildDocBookCatalog
profile    : |
    # Clear Inspiration.
    %make dba100000.xml
    ./xmllint --noout  dba100000.xml
    ./xmllint --stream  dba100000.xml
    ./xmllint --noout --valid test/valid/REC-xml-19980210.xml
    ./xmllint --stream --valid test/valid/REC-xml-19980210.xml
    %make check
check      : |
    %make check
